sudo: false
language: python

install: pip install -e .

script: 'true'  # No tests

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  skip_cleanup: true
  on:
    tags: true
    repo: opsdroid/image_size
